export const HOME_LIST_REQUEST = "@HomeReducer/HOME_LIST_REQUEST";
export const HOME_LIST_SUCCESS = "@HomeReducer/HOME_LIST_SUCCESS";
export const HOME_LIST_FAILED = "@HomeReducer/HOME_LIST_FAILED";

export const DELETE_SUCCESS = "@HomeReducer/DELETE_SUCCESS";
export const DELETE_FAILED = "@HomeReducer/DELETE_FAILED";

export const DELETE_USER_PROJECT_SUCCESS =
  "@HomeReducer/DELETE_USER_PROJECT_SUCCESS";
export const DELETE_USER_PROJECT_FAILED =
  "@HomeReducer/DELETE_USER_PROJECT_FAILED";

export const SEARCH_USER_SUCCESS = "@HomeReducer/SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAILED = "@HomeReducer/SEARCH_USER_FAILED";

export const ASIGN_USER_PROJECT_SUCCESS =
  "@HomeReducer/ASIGN_USER_PROJECT_SUCCESS";
export const ASIGN_USER_PROJECT_FAILED =
  "@HomeReducer/ASIGN_USER_PROJECT_FAILED";

export const CREATE_PROJECT_REQUEST = "@HomeReducer/CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "@HomeReducer/CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILED = "@HomeReducer/CREATE_PROJECT_FAILED";

export const GET_CATEGORY_SUCCESS = "@HomeReducer/GET_CATEGORY_SUCCESS";

export const GET_PROJECT_EDIT_SUCCESS = "@HomeReducer/GET_PROJECT_EDIT_SUCCESS";

export const EDIT_SUCCESS = "@HomeReducer/EDIT_SUCCESS ";

export const EDIT_FAILED = "@HomeReducer/EDIT_FAILED ";
